fix: convert airport elevation to feet
flybywiresim/msfs-navdata pull request #23
Opened 2023-10-24 20:17 UTC by BlueberryKing

Fixes #22

Convert airport elevation to feet.

2023-10-25 00:06 UTC, tracernz requested changes

2023-10-25 00:06 UTC, tracernz commented on src/client/backends/Msfs/Mapping.ts
> +            elevations.push(runway.elevation * 3.28084);
Use the exact conversion instead.
```suggestion
            elevations.push(runway.elevation / 0.3048);
```

2023-10-25 19:05 UTC, tracernz approved these changes

2023-10-28 00:22 UTC, Benjozork approved these changes

2023-10-28 00:32 UTC, merged