refactor: replace FixInfo with Fix type
flybywiresim/msfs-navdata pull request #7
Opened 2022-07-10 06:30 UTC by professoralex13

2022-07-11 17:58 UTC, Benjozork requested changes

2022-07-11 17:58 UTC, Benjozork commented on src/client/backends/External.ts
> +const fetch = require('node-fetch');
This will not work in browser

2022-07-13 05:30 UTC, tracernz requested changes
There are some very strange API choices. You've also made some strange unrelated changes that don't make much sense. Please revert those.

2022-07-13 05:30 UTC, tracernz commented on package.json
> +    "test": "jest --passWithNoTests"
What is the need for this, since we have multiple tests?

2022-07-13 05:30 UTC, tracernz commented on src/client/Database.spec.ts
> +});
This test can't really work in CI?? Suggest mocking the backend with some hand-made data from the AIP.

2022-07-13 05:30 UTC, tracernz commented on src/client/Database.ts
> +    public getEnrouteFixes<T extends FixTypeFlags>(idents: string[], airports?: string[], type?: T): Promise<EnrouteFix[]> {
How does airports make sense for enroute fixes? By definition they are not in a terminal area.

2022-07-13 05:30 UTC, tracernz commented on src/client/Database.ts
> +    public getAirportFixes<T extends FixTypeFlags>(idents: string[], airportIdentifier: string, type?: T): Promise<AirportFix[]> {
```suggestion
    public getTerminalFixes<T extends FixTypeFlags>(idents: string[], airportIdentifier: string, type?: T): Promise<AirportFix[]> {
```

2022-07-13 05:30 UTC, tracernz commented on src/client/Database.ts
> +        return Promise.all(promises).then((data) => data.flat());
This function should return all the terminal area fixes by it's name. Seems like a strange API as-is tbh.

2022-07-13 05:30 UTC, tracernz commented on src/client/Database.ts
> +        return Promise.all(promises).then((data) => data.flat());
Why is airports optional, but no results are ever returned without it?

2022-07-13 05:30 UTC, tracernz commented on src/client/backends/Msfs/Msfs.ts
> +            previousEffectiveFromTo: [previousStart, fromDate],
Why did you change this?? I explicitly made this an ISO standard format to avoid compatibility issues. The previous cycle is not a property of the current cycle db so not sure why you put it here?

2022-07-13 05:30 UTC, tracernz commented on src/client/backends/Msfs/Msfs.ts
> +        idents.forEach(async (ident) => {
This is worse :/. We aren't restricted to old school JS.

2022-07-13 05:30 UTC, tracernz commented on src/client/backends/Msfs/Msfs.ts
> +        });
Same again.

2022-07-13 05:30 UTC, tracernz commented on src/client/backends/Msfs/Msfs.ts
> +        });
Same again.

2022-07-13 05:30 UTC, tracernz commented on src/server/providers/navigraph_dfd/dfd.ts
>              };
As above, please revert all this.

2022-07-13 05:31 UTC, tracernz commented
Suggest narrowing the scope to just that required for the Fix type.

2022-07-13 06:04 UTC, tracernz commented on src/client/backends/Msfs/FacilityCache.ts
> +            return [...(await this.getFacilities(icaos, LoadType.Intersection))] as any as SearchedFacilityType<T>;
```suggestion
            return [...(await this.getFacilities(icaos, LoadType.Intersection)).values()] as any as SearchedFacilityType<T>;
```

2022-07-13 06:07 UTC, tracernz commented on src/shared/types/Common.ts
> +}
Should be in it's own file, along with the flags.

2022-08-28 04:38 UTC, tracernz commented on src/client/backends/Msfs/Mapping.ts
> +                    location: thresholdLocation,
This doesn't need to be a fix. This is data about a runway assocaited with an airport... not a fix associated with a procedure... that should be something different (e.g. that's what mapRunwayFix is for creating). Renaming this particular field loses linkage with associated fields (i.e. thresholdCrossingHeight).

2022-08-28 04:38 UTC, tracernz commented on src/client/backends/Msfs/Mapping.ts
> +                    location: thresholdLocation,
As above, no changes to the Runway type needed as it's not a fix.

2022-08-28 04:38 UTC, tracernz commented on src/client/backends/Msfs/Mapping.ts
> +                fixType: FixType.IlsNavaid,
This is also not a fix so no changes needed to this type. VhfNavaids cover this need.

2022-08-28 04:38 UTC, tracernz commented on src/client/backends/Msfs/Msfs.ts
> +        (await Promise.all(promises)).flat().forEach((v) => results.set(v.icao, this.mapping.mapFacilityToWaypoint(v)));
This change achieves nothing other than making the code even less readable with the old-school array methods. If the lint rules are counter-productive we should fix them instead. Same applies for the other two similar changes in this file.

2022-08-28 04:38 UTC, tracernz commented on src/server/providers/navigraph_dfd/mappers.ts
> +        }
This whole thing really just spreads the logic out and makes it less readable than before... Before it was very easy to see on one line what is considered terminal for example.

2022-08-28 04:38 UTC, tracernz commented on src/shared/types/Approach.ts
> +    Visual = 'VIS',
Should probably note in a JSDoc that this is for FMS implementation convenience and not from ARINC424

2022-08-28 04:38 UTC, tracernz commented on src/shared/types/Runway.ts
> +    fixType: FixType.Runway;
Not a fix, as in previous comments.

2022-10-08 01:36 UTC, closed without merging